# Generated by Django 5.0.6 on 2024-11-27 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("semaforos", "0001_initial"),
    ]

    operations = []
